# Site settings
title: Android Netrunner UK Rankings
tag_text: Android Netrunner UK Rankings

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

gdrive:
  sheet: "points"
